---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freediameter-amf-config
  namespace: {{ .Values.namespace }}
data:
  config.file: |-
      Identity = "amf.localdomain";
      Realm = "localdomain";
      No_SCTP;
      ListenOn = "{{ .Values.free5gc.amf.addr }}";
      TLS_Cred = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/amf.cert.pem", "/usr/src/free5gc/install/etc/free5gc/freeDiameter/amf.key.pem";
      TLS_CA = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
      LoadExtension = "dbg_msg_dumps.so" : "0x8888";
      LoadExtension = "dict_rfc5777.so";
      LoadExtension = "dict_mip6i.so";
      LoadExtension = "dict_nasreq.so";
      LoadExtension = "dict_nas_mipv6.so";
      LoadExtension = "dict_dcca.so";
      LoadExtension = "dict_dcca_3gpp.so";
      LoadExtension = "dict_s6a.so";
      ConnectPeer = "hss.localdomain" { ConnectTo = "{{ .Values.free5gc.hss.addr }}"; No_TLS; };

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: freediameter-hss-config
  namespace: {{ .Values.namespace }}
data:
  config.file: |-
      Identity = "hss.localdomain";
      Realm = "localdomain";
      No_SCTP;
      ListenOn = "{{ .Values.free5gc.hss.addr }}";
      TLS_Cred = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/hss.cert.pem", "/usr/src/free5gc/install/etc/free5gc/freeDiameter/hss.key.pem";
      TLS_CA = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
      LoadExtension = "dbg_msg_dumps.so" : "0x8888";
      LoadExtension = "dict_rfc5777.so";
      LoadExtension = "dict_mip6i.so";
      LoadExtension = "dict_nasreq.so";
      LoadExtension = "dict_nas_mipv6.so";
      LoadExtension = "dict_dcca.so";
      LoadExtension = "dict_dcca_3gpp.so";
      LoadExtension = "dict_s6a.so";
      ConnectPeer = "amf.localdomain" { ConnectTo = "{{ .Values.free5gc.amf.addr }}"; No_TLS; };

---

    
apiVersion: v1
kind: ConfigMap
metadata:
  name: freediameter-smf-config
  namespace: {{ .Values.namespace }}
data:
  config.file: |-
      Identity = "smf.localdomain";
      Realm = "localdomain";
      No_SCTP;
      ListenOn = "{{ .Values.free5gc.smf.addr }}";
      TLS_Cred = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/smf.cert.pem", "/usr/src/free5gc/install/etc/free5gc/freeDiameter/smf.key.pem";
      TLS_CA = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
      LoadExtension = "dbg_msg_dumps.so" : "0x8888";
      LoadExtension = "dict_rfc5777.so";
      LoadExtension = "dict_mip6i.so";
      LoadExtension = "dict_nasreq.so";
      LoadExtension = "dict_nas_mipv6.so";
      LoadExtension = "dict_dcca.so";
      LoadExtension = "dict_dcca_3gpp.so";
      ConnectPeer = "pcrf.localdomain" { ConnectTo = "{{ .Values.free5gc.pcrf.addr }}"; No_TLS; };

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: freediameter-pcrf-config
  namespace: {{ .Values.namespace }}
data:
  config.file: |
      Identity = "pcrf.localdomain";
      Realm = "localdomain";
      No_SCTP;
      ListenOn = "{{ .Values.free5gc.pcrf.addr }}";
      TLS_Cred = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/pcrf.cert.pem", "/usr/src/free5gc/install/etc/free5gc/freeDiameter/pcrf.key.pem";
      TLS_CA = "/usr/src/free5gc/install/etc/free5gc/freeDiameter/cacert.pem";
      LoadExtension = "dbg_msg_dumps.so" : "0x8888";
      LoadExtension = "dict_rfc5777.so";
      LoadExtension = "dict_mip6i.so";
      LoadExtension = "dict_nasreq.so";
      LoadExtension = "dict_nas_mipv6.so";
      LoadExtension = "dict_dcca.so";
      LoadExtension = "dict_dcca_3gpp.so";
      ConnectPeer = "smf.localdomain" { ConnectTo = "{{ .Values.free5gc.smf.addr }}"; No_TLS; };
