apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs
spec:
  storageClassName: mongo
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /nfsshare
    server: 192.168.26.11
  persistentVolumeReclaimPolicy: Recycle
