/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_TargetID.h"

#include "NGAP_TargetRANNodeID.h"
#include "NGAP_TargeteNB-ID.h"
static asn_oer_constraints_t asn_OER_type_NGAP_TargetID_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_NGAP_TargetID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_NGAP_TargetID_1[] = {
	{ ATF_POINTER, 0, offsetof(struct NGAP_TargetID, choice.targetRANNodeID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_TargetRANNodeID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetRANNodeID"
		},
	{ ATF_POINTER, 0, offsetof(struct NGAP_TargetID, choice.targeteNB_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_TargeteNB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targeteNB-ID"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_TargetID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* targetRANNodeID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* targeteNB-ID */
};
static asn_CHOICE_specifics_t asn_SPC_NGAP_TargetID_specs_1 = {
	sizeof(struct NGAP_TargetID),
	offsetof(struct NGAP_TargetID, _asn_ctx),
	offsetof(struct NGAP_TargetID, present),
	sizeof(((struct NGAP_TargetID *)0)->present),
	asn_MAP_NGAP_TargetID_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_TargetID = {
	"TargetID",
	"TargetID",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_NGAP_TargetID_constr_1, &asn_PER_type_NGAP_TargetID_constr_1, CHOICE_constraint },
	asn_MBR_NGAP_TargetID_1,
	2,	/* Elements count */
	&asn_SPC_NGAP_TargetID_specs_1	/* Additional specs */
};

