/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_ProtocolIE_Container_H_
#define	_NGAP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_PDUSessionResourceSetupRequestIEs;
struct NGAP_PDUSessionResourceSetupResponseIEs;
struct NGAP_PDUSessionResourceReleaseCommandIEs;
struct NGAP_PDUSessionResourceReleaseResponseIEs;
struct NGAP_PDUSessionResourceModifyRequestIEs;
struct NGAP_PDUSessionResourceModifyResponseIEs;
struct NGAP_PDUSessionResourceNotifyIEs;
struct NGAP_PDUSessionResourceModifyIndicationIEs;
struct NGAP_PDUSessionResourceModifyConfirmIEs;
struct NGAP_InitialContextSetupRequestIEs;
struct NGAP_InitialContextSetupResponseIEs;
struct NGAP_InitialContextSetupFailureIEs;
struct NGAP_UEContextReleaseRequest_IEs;
struct NGAP_UEContextReleaseCommand_IEs;
struct NGAP_UEContextReleaseComplete_IEs;
struct NGAP_UEContextModificationRequestIEs;
struct NGAP_UEContextModificationResponseIEs;
struct NGAP_UEContextModificationFailureIEs;
struct NGAP_HandoverRequiredIEs;
struct NGAP_HandoverCommandIEs;
struct NGAP_HandoverPreparationFailureIEs;
struct NGAP_HandoverRequestIEs;
struct NGAP_HandoverRequestAcknowledgeIEs;
struct NGAP_HandoverFailureIEs;
struct NGAP_HandoverNotifyIEs;
struct NGAP_PathSwitchRequestIEs;
struct NGAP_PathSwitchRequestAcknowledgeIEs;
struct NGAP_PathSwitchRequestFailureIEs;
struct NGAP_HandoverCancelIEs;
struct NGAP_HandoverCancelAcknowledgeIEs;
struct NGAP_UplinkRANStatusTransferIEs;
struct NGAP_DownlinkRANStatusTransferIEs;
struct NGAP_PagingIEs;
struct NGAP_InitialUEMessage_IEs;
struct NGAP_DownlinkNASTransport_IEs;
struct NGAP_UplinkNASTransport_IEs;
struct NGAP_NASNonDeliveryIndication_IEs;
struct NGAP_RerouteNASRequest_IEs;
struct NGAP_NGSetupRequestIEs;
struct NGAP_NGSetupResponseIEs;
struct NGAP_NGSetupFailureIEs;
struct NGAP_RANConfigurationUpdateIEs;
struct NGAP_RANConfigurationUpdateAcknowledgeIEs;
struct NGAP_RANConfigurationUpdateFailureIEs;
struct NGAP_AMFConfigurationUpdateIEs;
struct NGAP_AMFConfigurationUpdateAcknowledgeIEs;
struct NGAP_AMFConfigurationUpdateFailureIEs;
struct NGAP_AMFStatusIndicationIEs;
struct NGAP_NGResetIEs;
struct NGAP_NGResetAcknowledgeIEs;
struct NGAP_ErrorIndicationIEs;
struct NGAP_UplinkRANConfigurationTransferIEs;
struct NGAP_DownlinkRANConfigurationTransferIEs;
struct NGAP_WriteReplaceWarningRequestIEs;
struct NGAP_WriteReplaceWarningResponseIEs;
struct NGAP_PWSCancelRequestIEs;
struct NGAP_PWSCancelResponseIEs;
struct NGAP_PWSRestartIndicationIEs;
struct NGAP_PWSFailureIndicationIEs;
struct NGAP_DownlinkUEAssociatedNRPPaTransportIEs;
struct NGAP_UplinkUEAssociatedNRPPaTransportIEs;
struct NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct NGAP_UplinkNonUEAssociatedNRPPaTransportIEs;
struct NGAP_TraceStartIEs;
struct NGAP_TraceFailureIndicationIEs;
struct NGAP_DeactivateTraceIEs;
struct NGAP_CellTrafficTraceIEs;
struct NGAP_LocationReportingControlIEs;
struct NGAP_LocationReportingFailureIndicationIEs;
struct NGAP_LocationReportIEs;
struct NGAP_UETNLABindingReleaseRequestIEs;
struct NGAP_UECapabilityInfoIndicationIEs;
struct NGAP_UERadioCapabilityCheckRequestIEs;
struct NGAP_UERadioCapabilityCheckResponseIEs;

/* NGAP_ProtocolIE-Container */
typedef struct NGAP_ProtocolIE_Container_5540P0 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P0_t;
typedef struct NGAP_ProtocolIE_Container_5540P1 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P1_t;
typedef struct NGAP_ProtocolIE_Container_5540P2 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P2_t;
typedef struct NGAP_ProtocolIE_Container_5540P3 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P3_t;
typedef struct NGAP_ProtocolIE_Container_5540P4 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P4_t;
typedef struct NGAP_ProtocolIE_Container_5540P5 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P5_t;
typedef struct NGAP_ProtocolIE_Container_5540P6 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P6_t;
typedef struct NGAP_ProtocolIE_Container_5540P7 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P7_t;
typedef struct NGAP_ProtocolIE_Container_5540P8 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P8_t;
typedef struct NGAP_ProtocolIE_Container_5540P9 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P9_t;
typedef struct NGAP_ProtocolIE_Container_5540P10 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P10_t;
typedef struct NGAP_ProtocolIE_Container_5540P11 {
	A_SEQUENCE_OF(struct NGAP_InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P11_t;
typedef struct NGAP_ProtocolIE_Container_5540P12 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P12_t;
typedef struct NGAP_ProtocolIE_Container_5540P13 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P13_t;
typedef struct NGAP_ProtocolIE_Container_5540P14 {
	A_SEQUENCE_OF(struct NGAP_UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P14_t;
typedef struct NGAP_ProtocolIE_Container_5540P15 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P15_t;
typedef struct NGAP_ProtocolIE_Container_5540P16 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P16_t;
typedef struct NGAP_ProtocolIE_Container_5540P17 {
	A_SEQUENCE_OF(struct NGAP_UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P17_t;
typedef struct NGAP_ProtocolIE_Container_5540P18 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P18_t;
typedef struct NGAP_ProtocolIE_Container_5540P19 {
	A_SEQUENCE_OF(struct NGAP_HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P19_t;
typedef struct NGAP_ProtocolIE_Container_5540P20 {
	A_SEQUENCE_OF(struct NGAP_HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P20_t;
typedef struct NGAP_ProtocolIE_Container_5540P21 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P21_t;
typedef struct NGAP_ProtocolIE_Container_5540P22 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P22_t;
typedef struct NGAP_ProtocolIE_Container_5540P23 {
	A_SEQUENCE_OF(struct NGAP_HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P23_t;
typedef struct NGAP_ProtocolIE_Container_5540P24 {
	A_SEQUENCE_OF(struct NGAP_HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P24_t;
typedef struct NGAP_ProtocolIE_Container_5540P25 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P25_t;
typedef struct NGAP_ProtocolIE_Container_5540P26 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P26_t;
typedef struct NGAP_ProtocolIE_Container_5540P27 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P27_t;
typedef struct NGAP_ProtocolIE_Container_5540P28 {
	A_SEQUENCE_OF(struct NGAP_HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P28_t;
typedef struct NGAP_ProtocolIE_Container_5540P29 {
	A_SEQUENCE_OF(struct NGAP_HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P29_t;
typedef struct NGAP_ProtocolIE_Container_5540P30 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P30_t;
typedef struct NGAP_ProtocolIE_Container_5540P31 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P31_t;
typedef struct NGAP_ProtocolIE_Container_5540P32 {
	A_SEQUENCE_OF(struct NGAP_PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P32_t;
typedef struct NGAP_ProtocolIE_Container_5540P33 {
	A_SEQUENCE_OF(struct NGAP_InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P33_t;
typedef struct NGAP_ProtocolIE_Container_5540P34 {
	A_SEQUENCE_OF(struct NGAP_DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P34_t;
typedef struct NGAP_ProtocolIE_Container_5540P35 {
	A_SEQUENCE_OF(struct NGAP_UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P35_t;
typedef struct NGAP_ProtocolIE_Container_5540P36 {
	A_SEQUENCE_OF(struct NGAP_NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P36_t;
typedef struct NGAP_ProtocolIE_Container_5540P37 {
	A_SEQUENCE_OF(struct NGAP_RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P37_t;
typedef struct NGAP_ProtocolIE_Container_5540P38 {
	A_SEQUENCE_OF(struct NGAP_NGSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P38_t;
typedef struct NGAP_ProtocolIE_Container_5540P39 {
	A_SEQUENCE_OF(struct NGAP_NGSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P39_t;
typedef struct NGAP_ProtocolIE_Container_5540P40 {
	A_SEQUENCE_OF(struct NGAP_NGSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P40_t;
typedef struct NGAP_ProtocolIE_Container_5540P41 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P41_t;
typedef struct NGAP_ProtocolIE_Container_5540P42 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P42_t;
typedef struct NGAP_ProtocolIE_Container_5540P43 {
	A_SEQUENCE_OF(struct NGAP_RANConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P43_t;
typedef struct NGAP_ProtocolIE_Container_5540P44 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P44_t;
typedef struct NGAP_ProtocolIE_Container_5540P45 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P45_t;
typedef struct NGAP_ProtocolIE_Container_5540P46 {
	A_SEQUENCE_OF(struct NGAP_AMFConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P46_t;
typedef struct NGAP_ProtocolIE_Container_5540P47 {
	A_SEQUENCE_OF(struct NGAP_AMFStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P47_t;
typedef struct NGAP_ProtocolIE_Container_5540P48 {
	A_SEQUENCE_OF(struct NGAP_NGResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P48_t;
typedef struct NGAP_ProtocolIE_Container_5540P49 {
	A_SEQUENCE_OF(struct NGAP_NGResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P49_t;
typedef struct NGAP_ProtocolIE_Container_5540P50 {
	A_SEQUENCE_OF(struct NGAP_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P50_t;
typedef struct NGAP_ProtocolIE_Container_5540P51 {
	A_SEQUENCE_OF(struct NGAP_UplinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P51_t;
typedef struct NGAP_ProtocolIE_Container_5540P52 {
	A_SEQUENCE_OF(struct NGAP_DownlinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P52_t;
typedef struct NGAP_ProtocolIE_Container_5540P53 {
	A_SEQUENCE_OF(struct NGAP_WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P53_t;
typedef struct NGAP_ProtocolIE_Container_5540P54 {
	A_SEQUENCE_OF(struct NGAP_WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P54_t;
typedef struct NGAP_ProtocolIE_Container_5540P55 {
	A_SEQUENCE_OF(struct NGAP_PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P55_t;
typedef struct NGAP_ProtocolIE_Container_5540P56 {
	A_SEQUENCE_OF(struct NGAP_PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P56_t;
typedef struct NGAP_ProtocolIE_Container_5540P57 {
	A_SEQUENCE_OF(struct NGAP_PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P57_t;
typedef struct NGAP_ProtocolIE_Container_5540P58 {
	A_SEQUENCE_OF(struct NGAP_PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P58_t;
typedef struct NGAP_ProtocolIE_Container_5540P59 {
	A_SEQUENCE_OF(struct NGAP_DownlinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P59_t;
typedef struct NGAP_ProtocolIE_Container_5540P60 {
	A_SEQUENCE_OF(struct NGAP_UplinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P60_t;
typedef struct NGAP_ProtocolIE_Container_5540P61 {
	A_SEQUENCE_OF(struct NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P61_t;
typedef struct NGAP_ProtocolIE_Container_5540P62 {
	A_SEQUENCE_OF(struct NGAP_UplinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P62_t;
typedef struct NGAP_ProtocolIE_Container_5540P63 {
	A_SEQUENCE_OF(struct NGAP_TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P63_t;
typedef struct NGAP_ProtocolIE_Container_5540P64 {
	A_SEQUENCE_OF(struct NGAP_TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P64_t;
typedef struct NGAP_ProtocolIE_Container_5540P65 {
	A_SEQUENCE_OF(struct NGAP_DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P65_t;
typedef struct NGAP_ProtocolIE_Container_5540P66 {
	A_SEQUENCE_OF(struct NGAP_CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P66_t;
typedef struct NGAP_ProtocolIE_Container_5540P67 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P67_t;
typedef struct NGAP_ProtocolIE_Container_5540P68 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P68_t;
typedef struct NGAP_ProtocolIE_Container_5540P69 {
	A_SEQUENCE_OF(struct NGAP_LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P69_t;
typedef struct NGAP_ProtocolIE_Container_5540P70 {
	A_SEQUENCE_OF(struct NGAP_UETNLABindingReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P70_t;
typedef struct NGAP_ProtocolIE_Container_5540P71 {
	A_SEQUENCE_OF(struct NGAP_UECapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P71_t;
typedef struct NGAP_ProtocolIE_Container_5540P72 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P72_t;
typedef struct NGAP_ProtocolIE_Container_5540P73 {
	A_SEQUENCE_OF(struct NGAP_UERadioCapabilityCheckResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolIE_Container_5540P73_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P0;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P0_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P0_1[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P1;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P1_specs_3;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P1_3[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P2;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P2_specs_5;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P2_5[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P3;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P3_specs_7;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P3_7[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P4;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P4_specs_9;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P4_9[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P5;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P5_specs_11;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P5_11[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P6;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P6_specs_13;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P6_13[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P7;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P7_specs_15;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P7_15[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P8;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P8_specs_17;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P8_17[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P9;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P9_specs_19;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P9_19[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P10;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P10_specs_21;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P10_21[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P11;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P11_specs_23;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P11_23[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P12;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P12_specs_25;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P12_25[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P13;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P13_specs_27;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P13_27[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P14;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P14_specs_29;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P14_29[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P15;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P15_specs_31;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P15_31[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P16;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P16_specs_33;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P16_33[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P17;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P17_specs_35;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P17_35[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P18;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P18_specs_37;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P18_37[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P19;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P19_specs_39;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P19_39[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P20;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P20_specs_41;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P20_41[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P21;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P21_specs_43;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P21_43[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P22;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P22_specs_45;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P22_45[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P23;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P23_specs_47;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P23_47[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P24;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P24_specs_49;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P24_49[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P25;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P25_specs_51;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P25_51[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P26;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P26_specs_53;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P26_53[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P27;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P27_specs_55;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P27_55[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P28;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P28_specs_57;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P28_57[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P29;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P29_specs_59;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P29_59[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P30;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P30_specs_61;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P30_61[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P31;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P31_specs_63;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P31_63[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P32;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P32_specs_65;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P32_65[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P33;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P33_specs_67;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P33_67[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P34;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P34_specs_69;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P34_69[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P35;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P35_specs_71;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P35_71[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P36;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P36_specs_73;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P36_73[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P37;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P37_specs_75;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P37_75[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P38;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P38_specs_77;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P38_77[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P39;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P39_specs_79;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P39_79[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P40;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P40_specs_81;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P40_81[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P41;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P41_specs_83;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P41_83[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P42;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P42_specs_85;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P42_85[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P43;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P43_specs_87;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P43_87[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P44;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P44_specs_89;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P44_89[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P45;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P45_specs_91;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P45_91[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P46;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P46_specs_93;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P46_93[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P47;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P47_specs_95;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P47_95[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P48;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P48_specs_97;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P48_97[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P49;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P49_specs_99;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P49_99[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P50;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P50_specs_101;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P50_101[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P51;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P51_specs_103;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P51_103[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P52;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P52_specs_105;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P52_105[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P53;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P53_specs_107;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P53_107[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P54;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P54_specs_109;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P54_109[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P55;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P55_specs_111;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P55_111[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P56;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P56_specs_113;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P56_113[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P57;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P57_specs_115;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P57_115[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P58;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P58_specs_117;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P58_117[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P59;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P59_specs_119;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P59_119[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P60;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P60_specs_121;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P60_121[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P61;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P61_specs_123;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P61_123[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P62;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P62_specs_125;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P62_125[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P63;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P63_specs_127;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P63_127[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P64;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P64_specs_129;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P64_129[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P65;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P65_specs_131;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P65_131[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P66;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P66_specs_133;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P66_133[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P67;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P67_specs_135;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P67_135[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P68;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P68_specs_137;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P68_137[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P69;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P69_specs_139;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P69_139[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P70;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P70_specs_141;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P70_141[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P71;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P71_specs_143;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P71_143[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P72;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P72_specs_145;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P72_145[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_Container_5540P73;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolIE_Container_5540P73_specs_147;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolIE_Container_5540P73_147[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolIE_Container_5540P73_constr_147;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ProtocolIE_Container_H_ */
#include <asn_internal.h>
