/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_PDUSessionResourceSetupRequestTransfer.h"

#include "NGAP_UPTransportLayerInformation.h"
#include "NGAP_SecurityIndication.h"
#include "NGAP_ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_NGAP_PDUSessionResourceSetupRequestTransfer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, pDUSessionAggregateMaximumBitRate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDUSessionAggregateMaximumBitRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, uL_NGU_UP_TNLInformation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NGAP_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-NGU-UP-TNLInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, additionalUL_NGU_UP_TNLInformation),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NGAP_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalUL-NGU-UP-TNLInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, dataForwardingNotPossible),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_DataForwardingNotPossible,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataForwardingNotPossible"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, pDUSessionType),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_PDUSessionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDUSessionType"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, securityIndication),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_SecurityIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, qosFlowSetupRequestList),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_QosFlowSetupRequestList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qosFlowSetupRequestList"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_5591P78,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_PDUSessionResourceSetupRequestTransfer_oms_1[] = { 2, 3, 5, 7 };
static const ber_tlv_tag_t asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_PDUSessionResourceSetupRequestTransfer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pDUSessionAggregateMaximumBitRate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uL-NGU-UP-TNLInformation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* additionalUL-NGU-UP-TNLInformation */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dataForwardingNotPossible */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pDUSessionType */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* securityIndication */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* qosFlowSetupRequestList */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_NGAP_PDUSessionResourceSetupRequestTransfer_specs_1 = {
	sizeof(struct NGAP_PDUSessionResourceSetupRequestTransfer),
	offsetof(struct NGAP_PDUSessionResourceSetupRequestTransfer, _asn_ctx),
	asn_MAP_NGAP_PDUSessionResourceSetupRequestTransfer_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_NGAP_PDUSessionResourceSetupRequestTransfer_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer = {
	"PDUSessionResourceSetupRequestTransfer",
	"PDUSessionResourceSetupRequestTransfer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1,
	sizeof(asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1)
		/sizeof(asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1[0]), /* 1 */
	asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1)
		/sizeof(asn_DEF_NGAP_PDUSessionResourceSetupRequestTransfer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSetupRequestTransfer_1,
	8,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSetupRequestTransfer_specs_1	/* Additional specs */
};

