/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_UEPagingIdentity_H_
#define	_NGAP_UEPagingIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_UEPagingIdentity_PR {
	NGAP_UEPagingIdentity_PR_NOTHING,	/* No components present */
	NGAP_UEPagingIdentity_PR_fiveG_S_TMSI
	/* Extensions may appear below */
	
} NGAP_UEPagingIdentity_PR;

/* Forward declarations */
struct NGAP_FiveG_S_TMSI;

/* NGAP_UEPagingIdentity */
typedef struct NGAP_UEPagingIdentity {
	NGAP_UEPagingIdentity_PR present;
	union NGAP_UEPagingIdentity_u {
		struct NGAP_FiveG_S_TMSI	*fiveG_S_TMSI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_UEPagingIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UEPagingIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UEPagingIdentity_H_ */
#include <asn_internal.h>
