/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_N3IWF_ID_H_
#define	_NGAP_N3IWF_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_N3IWF_ID_PR {
	NGAP_N3IWF_ID_PR_NOTHING,	/* No components present */
	NGAP_N3IWF_ID_PR_n3IWF_ID
	/* Extensions may appear below */
	
} NGAP_N3IWF_ID_PR;

/* NGAP_N3IWF-ID */
typedef struct NGAP_N3IWF_ID {
	NGAP_N3IWF_ID_PR present;
	union NGAP_N3IWF_ID_u {
		BIT_STRING_t	 n3IWF_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_N3IWF_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_N3IWF_ID;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_N3IWF_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_N3IWF_ID_1[1];
extern asn_per_constraints_t asn_PER_type_NGAP_N3IWF_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_N3IWF_ID_H_ */
#include <asn_internal.h>
