/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using NGAP_PDUSessionResourceSetupItemSUReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceSetupItemSUResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceModifyItemModReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceModifyItemModResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceNotifyItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceModifyItemModIndIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceModifyItemModCfmIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceSetupItemCxtReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceSetupItemCxtResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceItemHORqdIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceSubjectToForwardingItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceSetupItemHOReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceAdmittedItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceToBeSwitchedDLItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PDUSessionResourceToBeSwitchedULItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_TAIItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_AMF_TNLAssociationToAddItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_AMF_TNLAssociationToRemoveItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_AMF_TNLAssociationToUpdateItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_AMF_TNLAssociationSetupItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UE_associatedLogicalNG_ConnectionItemResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UE_associatedLogicalNG_ConnectionItemResAck,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSetupItemSUReqIEs_1,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSetupItemSUReqIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P1_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSetupItemSUResIEs_5,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSetupItemSUResIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P2_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceModifyItemModReqIEs_9,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceModifyItemModReqIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P3_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceModifyItemModResIEs_13,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceModifyItemModResIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P4_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceNotifyItemIEs_17,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceNotifyItemIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P5_tags_6[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceModifyItemModIndIEs_21,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceModifyItemModIndIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P6_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceModifyItemModCfmIEs_25,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceModifyItemModCfmIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P7_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSetupItemCxtReqIEs_29,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSetupItemCxtReqIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P8_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSetupItemCxtResIEs_33,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSetupItemCxtResIEs_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P9_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceItemHORqdIEs_37,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceItemHORqdIEs_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P10_tags_11[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSubjectToForwardingItemIEs_41,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSubjectToForwardingItemIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P11_tags_12[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceSetupItemHOReqIEs_45,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceSetupItemHOReqIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P12_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceAdmittedItemIEs_49,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceAdmittedItemIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P13_tags_14[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceToBeSwitchedDLItemIEs_53,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceToBeSwitchedDLItemIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P14_tags_15[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceToBeSwitchedULItemIEs_57,
	3,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceToBeSwitchedULItemIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P15_tags_16[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_TAIItemIEs_61,
	3,	/* Elements count */
	&asn_SPC_NGAP_TAIItemIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P16_tags_17[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_AMF_TNLAssociationToAddItemIEs_65,
	3,	/* Elements count */
	&asn_SPC_NGAP_AMF_TNLAssociationToAddItemIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P17_tags_18[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_AMF_TNLAssociationToRemoveItemIEs_69,
	3,	/* Elements count */
	&asn_SPC_NGAP_AMF_TNLAssociationToRemoveItemIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P18_tags_19[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_AMF_TNLAssociationToUpdateItemIEs_73,
	3,	/* Elements count */
	&asn_SPC_NGAP_AMF_TNLAssociationToUpdateItemIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P19_tags_20[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_AMF_TNLAssociationSetupItemIEs_77,
	3,	/* Elements count */
	&asn_SPC_NGAP_AMF_TNLAssociationSetupItemIEs_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P20_tags_21[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UE_associatedLogicalNG_ConnectionItemResIEs_81,
	3,	/* Elements count */
	&asn_SPC_NGAP_UE_associatedLogicalNG_ConnectionItemResIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_5543P21_tags_22[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UE_associatedLogicalNG_ConnectionItemResAck_85,
	3,	/* Elements count */
	&asn_SPC_NGAP_UE_associatedLogicalNG_ConnectionItemResAck_specs_85	/* Additional specs */
};

