/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_UE_associatedLogicalNG_ConnectionItem_H_
#define	_NGAP_UE_associatedLogicalNG_ConnectionItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_AMF-UE-NGAP-ID.h"
#include "NGAP_RAN-UE-NGAP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_ProtocolExtensionContainer;

/* NGAP_UE-associatedLogicalNG-ConnectionItem */
typedef struct NGAP_UE_associatedLogicalNG_ConnectionItem {
	NGAP_AMF_UE_NGAP_ID_t	*aMF_UE_NGAP_ID;	/* OPTIONAL */
	NGAP_RAN_UE_NGAP_ID_t	*rAN_UE_NGAP_ID;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_UE_associatedLogicalNG_ConnectionItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UE_associatedLogicalNG_ConnectionItem;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UE_associatedLogicalNG_ConnectionItem_H_ */
#include <asn_internal.h>
