/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_CauseRadioNetwork.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_NGAP_CauseRadioNetwork_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_NGAP_CauseRadioNetwork_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  6,  6,  0,  41 }	/* (0..41,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_NGAP_CauseRadioNetwork_value2enum_1[] = {
	{ 0,	11,	"unspecified" },
	{ 1,	22,	"txnrelocoverall-expiry" },
	{ 2,	19,	"successful-handover" },
	{ 3,	37,	"release-due-to-ngran-generated-reason" },
	{ 4,	35,	"release-due-to-5gc-generated-reason" },
	{ 5,	18,	"handover-cancelled" },
	{ 6,	16,	"partial-handover" },
	{ 7,	52,	"ho-failure-in-target-5GC-ngran-node-or-target-system" },
	{ 8,	21,	"ho-target-not-allowed" },
	{ 9,	22,	"tngrelocoverall-expiry" },
	{ 10,	19,	"tngrelocprep-expiry" },
	{ 11,	18,	"cell-not-available" },
	{ 12,	16,	"unknown-targetID" },
	{ 13,	43,	"no-radio-resources-available-in-target-cell" },
	{ 14,	24,	"unknown-local-UE-NGAP-ID" },
	{ 15,	30,	"inconsistent-remote-UE-NGAP-ID" },
	{ 16,	35,	"handover-desirable-for-radio-reason" },
	{ 17,	22,	"time-critical-handover" },
	{ 18,	30,	"resource-optimisation-handover" },
	{ 19,	27,	"reduce-load-in-serving-cell" },
	{ 20,	15,	"user-inactivity" },
	{ 21,	29,	"radio-connection-with-ue-lost" },
	{ 22,	27,	"load-balancing-tau-required" },
	{ 23,	29,	"radio-resources-not-available" },
	{ 24,	23,	"invalid-qos-combination" },
	{ 25,	36,	"failure-in-radio-interface-procedure" },
	{ 26,	32,	"interaction-with-other-procedure" },
	{ 27,	22,	"unknown-PDU-session-ID" },
	{ 28,	18,	"unkown-qos-flow-ID" },
	{ 29,	33,	"multiple-PDU-session-ID-instances" },
	{ 30,	30,	"multiple-qos-flow-ID-instances" },
	{ 31,	63,	"encryption-and-or-integrity-protection-algorithms-not-supported" },
	{ 32,	34,	"ng-intra-system-handover-triggered" },
	{ 33,	34,	"ng-inter-system-handover-triggered" },
	{ 34,	21,	"xn-handover-triggered" },
	{ 35,	23,	"not-supported-5QI-value" },
	{ 36,	19,	"ue-context-transfer" },
	{ 37,	48,	"ims-voice-eps-fallback-or-rat-fallback-triggered" },
	{ 38,	36,	"up-integrity-protection-not-possible" },
	{ 39,	42,	"up-confidentiality-protection-not-possible" },
	{ 40,	19,	"slice-not-supported" },
	{ 41,	38,	"ue-in-rrc-inactive-state-not-reachable" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NGAP_CauseRadioNetwork_enum2value_1[] = {
	11,	/* cell-not-available(11) */
	31,	/* encryption-and-or-integrity-protection-algorithms-not-supported(31) */
	25,	/* failure-in-radio-interface-procedure(25) */
	5,	/* handover-cancelled(5) */
	16,	/* handover-desirable-for-radio-reason(16) */
	7,	/* ho-failure-in-target-5GC-ngran-node-or-target-system(7) */
	8,	/* ho-target-not-allowed(8) */
	37,	/* ims-voice-eps-fallback-or-rat-fallback-triggered(37) */
	15,	/* inconsistent-remote-UE-NGAP-ID(15) */
	26,	/* interaction-with-other-procedure(26) */
	24,	/* invalid-qos-combination(24) */
	22,	/* load-balancing-tau-required(22) */
	29,	/* multiple-PDU-session-ID-instances(29) */
	30,	/* multiple-qos-flow-ID-instances(30) */
	33,	/* ng-inter-system-handover-triggered(33) */
	32,	/* ng-intra-system-handover-triggered(32) */
	13,	/* no-radio-resources-available-in-target-cell(13) */
	35,	/* not-supported-5QI-value(35) */
	6,	/* partial-handover(6) */
	21,	/* radio-connection-with-ue-lost(21) */
	23,	/* radio-resources-not-available(23) */
	19,	/* reduce-load-in-serving-cell(19) */
	4,	/* release-due-to-5gc-generated-reason(4) */
	3,	/* release-due-to-ngran-generated-reason(3) */
	18,	/* resource-optimisation-handover(18) */
	40,	/* slice-not-supported(40) */
	2,	/* successful-handover(2) */
	17,	/* time-critical-handover(17) */
	9,	/* tngrelocoverall-expiry(9) */
	10,	/* tngrelocprep-expiry(10) */
	1,	/* txnrelocoverall-expiry(1) */
	36,	/* ue-context-transfer(36) */
	41,	/* ue-in-rrc-inactive-state-not-reachable(41) */
	27,	/* unknown-PDU-session-ID(27) */
	14,	/* unknown-local-UE-NGAP-ID(14) */
	12,	/* unknown-targetID(12) */
	28,	/* unkown-qos-flow-ID(28) */
	0,	/* unspecified(0) */
	39,	/* up-confidentiality-protection-not-possible(39) */
	38,	/* up-integrity-protection-not-possible(38) */
	20,	/* user-inactivity(20) */
	34	/* xn-handover-triggered(34) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_NGAP_CauseRadioNetwork_specs_1 = {
	asn_MAP_NGAP_CauseRadioNetwork_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_NGAP_CauseRadioNetwork_enum2value_1,	/* N => "tag"; sorted by N */
	42,	/* Number of elements in the maps */
	43,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NGAP_CauseRadioNetwork_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_CauseRadioNetwork = {
	"CauseRadioNetwork",
	"CauseRadioNetwork",
	&asn_OP_NativeEnumerated,
	asn_DEF_NGAP_CauseRadioNetwork_tags_1,
	sizeof(asn_DEF_NGAP_CauseRadioNetwork_tags_1)
		/sizeof(asn_DEF_NGAP_CauseRadioNetwork_tags_1[0]), /* 1 */
	asn_DEF_NGAP_CauseRadioNetwork_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_CauseRadioNetwork_tags_1)
		/sizeof(asn_DEF_NGAP_CauseRadioNetwork_tags_1[0]), /* 1 */
	{ &asn_OER_type_NGAP_CauseRadioNetwork_constr_1, &asn_PER_type_NGAP_CauseRadioNetwork_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NGAP_CauseRadioNetwork_specs_1	/* Additional specs */
};

