/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_ProtocolExtensionContainer_H_
#define	_NGAP_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_PDUSessionResourceSetupItemSUReq_ExtIEs;
struct NGAP_PDUSessionResourceSetupItemSURes_ExtIEs;
struct NGAP_PDUSessionResourceModifyItemModReq_ExtIEs;
struct NGAP_PDUSessionResourceModifyItemModRes_ExtIEs;
struct NGAP_PDUSessionResourceNotifyItem_ExtIEs;
struct NGAP_PDUSessionResourceModifyItemModInd_ExtIEs;
struct NGAP_PDUSessionResourceModifyItemModCfm_ExtIEs;
struct NGAP_PDUSessionResourceSetupItemCxtReq_ExtIEs;
struct NGAP_PDUSessionResourceSetupItemCxtRes_ExtIEs;
struct NGAP_PDUSessionResourceItemHORqd_ExtIEs;
struct NGAP_PDUSessionResourceSubjectToForwardingItem_ExtIEs;
struct NGAP_PDUSessionResourceSetupItemHOReq_ExtIEs;
struct NGAP_PDUSessionResourceAdmittedItem_ExtIEs;
struct NGAP_PDUSessionResourceToBeSwitchedDLItem_ExtIEs;
struct NGAP_PDUSessionResourceToBeSwitchedULItem_ExtIEs;
struct NGAP_TAIItem_ExtIEs;
struct NGAP_AMF_TNLAssociationToAddItem_ExtIEs;
struct NGAP_AMF_TNLAssociationToRemoveItem_ExtIEs;
struct NGAP_AMF_TNLAssociationToUpdateItem_ExtIEs;
struct NGAP_AMF_TNLAssociationSetupItem_ExtIEs;
struct NGAP_AllocationAndRetentionPriority_ExtIEs;
struct NGAP_AllowedNSSAI_Item_ExtIEs;
struct NGAP_AreaOfInterest_ExtIEs;
struct NGAP_AreaOfInterestItem_ExtIEs;
struct NGAP_AreaOfInterestTAIItem_ExtIEs;
struct NGAP_AssistanceDataForPaging_ExtIEs;
struct NGAP_AssistanceDataForRecommendedCells_ExtIEs;
struct NGAP_AssociatedQosFlowItem_ExtIEs;
struct NGAP_BroadcastPLMNItem_ExtIEs;
struct NGAP_CancelledCellsInEAI_EUTRA_Item_ExtIEs;
struct NGAP_CancelledCellsInEAI_NR_Item_ExtIEs;
struct NGAP_CancelledCellsInTAI_EUTRA_Item_ExtIEs;
struct NGAP_CancelledCellsInTAI_NR_Item_ExtIEs;
struct NGAP_CellIDBroadcastEUTRA_Item_ExtIEs;
struct NGAP_CellIDBroadcastNR_Item_ExtIEs;
struct NGAP_CellIDCancelledEUTRA_Item_ExtIEs;
struct NGAP_CellIDCancelledNR_Item_ExtIEs;
struct NGAP_CompletedCellsInEAI_EUTRA_Item_ExtIEs;
struct NGAP_CompletedCellsInEAI_NR_Item_ExtIEs;
struct NGAP_CompletedCellsInTAI_EUTRA_Item_ExtIEs;
struct NGAP_CompletedCellsInTAI_NR_Item_ExtIEs;
struct NGAP_CriticalityDiagnostics_ExtIEs;
struct NGAP_CriticalityDiagnostics_IE_Item_ExtIEs;
struct NGAP_DataForwardingResponseDRBItem_ExtIEs;
struct NGAP_DRBsToQosFlowsMappingItem_ExtIEs;
struct NGAP_Dynamic5QIDescriptor_ExtIEs;
struct NGAP_EmergencyAreaIDBroadcastEUTRA_Item_ExtIEs;
struct NGAP_EmergencyAreaIDBroadcastNR_Item_ExtIEs;
struct NGAP_EmergencyAreaIDCancelledEUTRA_Item_ExtIEs;
struct NGAP_EmergencyAreaIDCancelledNR_Item_ExtIEs;
struct NGAP_EPS_TAI_ExtIEs;
struct NGAP_E_RABInformationItem_ExtIEs;
struct NGAP_EUTRA_CGI_ExtIEs;
struct NGAP_FiveG_S_TMSI_ExtIEs;
struct NGAP_ForbiddenAreaInformation_Item_ExtIEs;
struct NGAP_GBR_QosInformation_ExtIEs;
struct NGAP_GlobalGNB_ID_ExtIEs;
struct NGAP_GlobalN3IWF_ID_ExtIEs;
struct NGAP_GlobalNgENB_ID_ExtIEs;
struct NGAP_GTPTunnel_ExtIEs;
struct NGAP_GUAMI_ExtIEs;
struct NGAP_HandoverCommandTransfer_ExtIEs;
struct NGAP_HandoverRequestAcknowledgeTransfer_ExtIEs;
struct NGAP_MobilityRestrictionList_ExtIEs;
struct NGAP_LocationReportingRequestType_ExtIEs;
struct NGAP_MultipleTNLInformation_ExtIEs;
struct NGAP_NonDynamic5QIDescriptor_ExtIEs;
struct NGAP_NR_CGI_ExtIEs;
struct NGAP_PagingAttemptInformation_ExtIEs;
struct NGAP_PathSwitchRequestAcknowledgeTransfer_ExtIEs;
struct NGAP_PathSwitchRequestTransfer_ExtIEs;
struct NGAP_PDUSessionItem_ExtIEs;
struct NGAP_PDUSessionResourceInformationItem_ExtIEs;
struct NGAP_PDUSessionResourceModifyConfirmTransfer_ExtIEs;
struct NGAP_PDUSessionResourceModifyRequestTransfer_ExtIEs;
struct NGAP_PDUSessionResourceModifyResponseTransfer_ExtIEs;
struct NGAP_PDUSessionResourceModifyIndicationTransfer_ExtIEs;
struct NGAP_PDUSessionResourceNotifyTransfer_ExtIEs;
struct NGAP_PDUSessionResourceSetupRequestTransfer_ExtIEs;
struct NGAP_PDUSessionResourceSetupResponseTransfer_ExtIEs;
struct NGAP_PLMNSupportItem_ExtIEs;
struct NGAP_QosFlowAcceptedItem_ExtIEs;
struct NGAP_QosFlowAddOrModifyRequestItem_ExtIEs;
struct NGAP_QosFlowAddOrModifyResponseItem_ExtIEs;
struct NGAP_QosFlowInformationItem_ExtIEs;
struct NGAP_QosFlowLevelQosParameters_ExtIEs;
struct NGAP_QosFlowItem_ExtIEs;
struct NGAP_QosFlowMappingItem_ExtIEs;
struct NGAP_QosFlowModifyConfirmItem_ExtIEs;
struct NGAP_QosFlowNotifyItem_ExtIEs;
struct NGAP_QosFlowSetupRequestItem_ExtIEs;
struct NGAP_QosFlowSetupResponseItemHOReqAck_ExtIEs;
struct NGAP_QosFlowSetupResponseItemSURes_ExtIEs;
struct NGAP_QosFlowToBeForwardedItem_ExtIEs;
struct NGAP_RATRestrictions_Item_ExtIEs;
struct NGAP_RecommendedCellsForPaging_ExtIEs;
struct NGAP_RecommendedCellItem_ExtIEs;
struct NGAP_RRCInactiveAssistanceInformation_ExtIEs;
struct NGAP_SecurityContext_ExtIEs;
struct NGAP_SecurityIndication_ExtIEs;
struct NGAP_SecurityResult_ExtIEs;
struct NGAP_ServedGUAMIItem_ExtIEs;
struct NGAP_ServiceAreaInformation_Item_ExtIEs;
struct NGAP_SingleTNLInformation_ExtIEs;
struct NGAP_SliceSupportItem_ExtIEs;
struct NGAP_S_NSSAI_ExtIEs;
struct NGAP_SONConfigurationTransfer_ExtIEs;
struct NGAP_SONInformationReply_ExtIEs;
struct NGAP_SourceNGRANNode_ToTargetNGRANNode_TransparentContainer_ExtIEs;
struct NGAP_SourceRANNodeID_ExtIEs;
struct NGAP_SupportedTAItem_ExtIEs;
struct NGAP_TAI_ExtIEs;
struct NGAP_TAIBroadcastEUTRA_Item_ExtIEs;
struct NGAP_TAIBroadcastNR_Item_ExtIEs;
struct NGAP_TAICancelledEUTRA_Item_ExtIEs;
struct NGAP_TAICancelledNR_Item_ExtIEs;
struct NGAP_RRCInactiveTAIItem_ExtIEs;
struct NGAP_TargeteNB_ID_ExtIEs;
struct NGAP_TargetNGRANNode_ToSourceNGRANNode_TransparentContainer_ExtIEs;
struct NGAP_TargetRANNodeID_ExtIEs;
struct NGAP_TNLAssociationItem_ExtIEs;
struct NGAP_TNLInformationItem_ExtIEs;
struct NGAP_TraceActivation_ExtIEs;
struct NGAP_UEAggregateMaximumBitRate_ExtIEs;
struct NGAP_UE_associatedLogicalNG_ConnectionItem_ExtIEs;
struct NGAP_UE_NGAP_ID_pair_ExtIEs;
struct NGAP_UEPresenceInAreaOfInterestItem_ExtIEs;
struct NGAP_UESecurityCapabilities_ExtIEs;
struct NGAP_UnavailableGUAMIItem_ExtIEs;
struct NGAP_UserLocationInformationEUTRA_ExtIEs;
struct NGAP_UserLocationInformationN3IWF_ExtIEs;
struct NGAP_UserLocationInformationNR_ExtIEs;
struct NGAP_UserPlaneSecurityInformation_ExtIEs;
struct NGAP_XnExtTLA_Item_ExtIEs;
struct NGAP_XnTNLConfigurationInfo_ExtIEs;

/* NGAP_ProtocolExtensionContainer */
typedef struct NGAP_ProtocolExtensionContainer_5591P0 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupItemSUReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P0_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P1 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupItemSURes_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P1_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P2 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyItemModReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P2_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P3 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyItemModRes_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P3_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P4 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceNotifyItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P4_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P5 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyItemModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P5_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P6 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyItemModCfm_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P6_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P7 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupItemCxtReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P7_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P8 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupItemCxtRes_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P8_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P9 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceItemHORqd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P9_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P10 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSubjectToForwardingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P10_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P11 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupItemHOReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P11_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P12 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceAdmittedItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P12_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P13 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceToBeSwitchedDLItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P13_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P14 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceToBeSwitchedULItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P14_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P15 {
	A_SEQUENCE_OF(struct NGAP_TAIItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P15_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P16 {
	A_SEQUENCE_OF(struct NGAP_AMF_TNLAssociationToAddItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P16_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P17 {
	A_SEQUENCE_OF(struct NGAP_AMF_TNLAssociationToRemoveItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P17_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P18 {
	A_SEQUENCE_OF(struct NGAP_AMF_TNLAssociationToUpdateItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P18_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P19 {
	A_SEQUENCE_OF(struct NGAP_AMF_TNLAssociationSetupItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P19_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P20 {
	A_SEQUENCE_OF(struct NGAP_AllocationAndRetentionPriority_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P20_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P21 {
	A_SEQUENCE_OF(struct NGAP_AllowedNSSAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P21_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P22 {
	A_SEQUENCE_OF(struct NGAP_AreaOfInterest_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P22_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P23 {
	A_SEQUENCE_OF(struct NGAP_AreaOfInterestItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P23_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P24 {
	A_SEQUENCE_OF(struct NGAP_AreaOfInterestTAIItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P24_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P25 {
	A_SEQUENCE_OF(struct NGAP_AssistanceDataForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P25_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P26 {
	A_SEQUENCE_OF(struct NGAP_AssistanceDataForRecommendedCells_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P26_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P27 {
	A_SEQUENCE_OF(struct NGAP_AssociatedQosFlowItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P27_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P28 {
	A_SEQUENCE_OF(struct NGAP_BroadcastPLMNItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P28_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P29 {
	A_SEQUENCE_OF(struct NGAP_CancelledCellsInEAI_EUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P29_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P30 {
	A_SEQUENCE_OF(struct NGAP_CancelledCellsInEAI_NR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P30_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P31 {
	A_SEQUENCE_OF(struct NGAP_CancelledCellsInTAI_EUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P31_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P32 {
	A_SEQUENCE_OF(struct NGAP_CancelledCellsInTAI_NR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P32_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P33 {
	A_SEQUENCE_OF(struct NGAP_CellIDBroadcastEUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P33_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P34 {
	A_SEQUENCE_OF(struct NGAP_CellIDBroadcastNR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P34_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P35 {
	A_SEQUENCE_OF(struct NGAP_CellIDCancelledEUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P35_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P36 {
	A_SEQUENCE_OF(struct NGAP_CellIDCancelledNR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P36_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P37 {
	A_SEQUENCE_OF(struct NGAP_CompletedCellsInEAI_EUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P37_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P38 {
	A_SEQUENCE_OF(struct NGAP_CompletedCellsInEAI_NR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P38_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P39 {
	A_SEQUENCE_OF(struct NGAP_CompletedCellsInTAI_EUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P39_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P40 {
	A_SEQUENCE_OF(struct NGAP_CompletedCellsInTAI_NR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P40_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P41 {
	A_SEQUENCE_OF(struct NGAP_CriticalityDiagnostics_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P41_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P42 {
	A_SEQUENCE_OF(struct NGAP_CriticalityDiagnostics_IE_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P42_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P43 {
	A_SEQUENCE_OF(struct NGAP_DataForwardingResponseDRBItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P43_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P44 {
	A_SEQUENCE_OF(struct NGAP_DRBsToQosFlowsMappingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P44_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P45 {
	A_SEQUENCE_OF(struct NGAP_Dynamic5QIDescriptor_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P45_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P46 {
	A_SEQUENCE_OF(struct NGAP_EmergencyAreaIDBroadcastEUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P46_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P47 {
	A_SEQUENCE_OF(struct NGAP_EmergencyAreaIDBroadcastNR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P47_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P48 {
	A_SEQUENCE_OF(struct NGAP_EmergencyAreaIDCancelledEUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P48_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P49 {
	A_SEQUENCE_OF(struct NGAP_EmergencyAreaIDCancelledNR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P49_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P50 {
	A_SEQUENCE_OF(struct NGAP_EPS_TAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P50_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P51 {
	A_SEQUENCE_OF(struct NGAP_E_RABInformationItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P51_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P52 {
	A_SEQUENCE_OF(struct NGAP_EUTRA_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P52_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P53 {
	A_SEQUENCE_OF(struct NGAP_FiveG_S_TMSI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P53_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P54 {
	A_SEQUENCE_OF(struct NGAP_ForbiddenAreaInformation_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P54_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P55 {
	A_SEQUENCE_OF(struct NGAP_GBR_QosInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P55_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P56 {
	A_SEQUENCE_OF(struct NGAP_GlobalGNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P56_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P57 {
	A_SEQUENCE_OF(struct NGAP_GlobalN3IWF_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P57_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P58 {
	A_SEQUENCE_OF(struct NGAP_GlobalNgENB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P58_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P59 {
	A_SEQUENCE_OF(struct NGAP_GTPTunnel_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P59_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P60 {
	A_SEQUENCE_OF(struct NGAP_GUAMI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P60_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P61 {
	A_SEQUENCE_OF(struct NGAP_HandoverCommandTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P61_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P62 {
	A_SEQUENCE_OF(struct NGAP_HandoverRequestAcknowledgeTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P62_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P63 {
	A_SEQUENCE_OF(struct NGAP_MobilityRestrictionList_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P63_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P64 {
	A_SEQUENCE_OF(struct NGAP_LocationReportingRequestType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P64_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P65 {
	A_SEQUENCE_OF(struct NGAP_MultipleTNLInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P65_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P66 {
	A_SEQUENCE_OF(struct NGAP_NonDynamic5QIDescriptor_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P66_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P67 {
	A_SEQUENCE_OF(struct NGAP_NR_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P67_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P68 {
	A_SEQUENCE_OF(struct NGAP_PagingAttemptInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P68_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P69 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestAcknowledgeTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P69_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P70 {
	A_SEQUENCE_OF(struct NGAP_PathSwitchRequestTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P70_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P71 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P71_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P72 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceInformationItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P72_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P73 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyConfirmTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P73_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P74 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyRequestTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P74_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P75 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyResponseTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P75_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P76 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceModifyIndicationTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P76_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P77 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceNotifyTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P77_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P78 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupRequestTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P78_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P79 {
	A_SEQUENCE_OF(struct NGAP_PDUSessionResourceSetupResponseTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P79_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P80 {
	A_SEQUENCE_OF(struct NGAP_PLMNSupportItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P80_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P81 {
	A_SEQUENCE_OF(struct NGAP_QosFlowAcceptedItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P81_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P82 {
	A_SEQUENCE_OF(struct NGAP_QosFlowAddOrModifyRequestItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P82_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P83 {
	A_SEQUENCE_OF(struct NGAP_QosFlowAddOrModifyResponseItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P83_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P84 {
	A_SEQUENCE_OF(struct NGAP_QosFlowInformationItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P84_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P85 {
	A_SEQUENCE_OF(struct NGAP_QosFlowLevelQosParameters_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P85_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P86 {
	A_SEQUENCE_OF(struct NGAP_QosFlowItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P86_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P87 {
	A_SEQUENCE_OF(struct NGAP_QosFlowMappingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P87_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P88 {
	A_SEQUENCE_OF(struct NGAP_QosFlowModifyConfirmItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P88_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P89 {
	A_SEQUENCE_OF(struct NGAP_QosFlowNotifyItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P89_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P90 {
	A_SEQUENCE_OF(struct NGAP_QosFlowSetupRequestItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P90_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P91 {
	A_SEQUENCE_OF(struct NGAP_QosFlowSetupResponseItemHOReqAck_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P91_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P92 {
	A_SEQUENCE_OF(struct NGAP_QosFlowSetupResponseItemSURes_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P92_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P93 {
	A_SEQUENCE_OF(struct NGAP_QosFlowToBeForwardedItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P93_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P94 {
	A_SEQUENCE_OF(struct NGAP_RATRestrictions_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P94_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P95 {
	A_SEQUENCE_OF(struct NGAP_RecommendedCellsForPaging_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P95_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P96 {
	A_SEQUENCE_OF(struct NGAP_RecommendedCellItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P96_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P97 {
	A_SEQUENCE_OF(struct NGAP_RRCInactiveAssistanceInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P97_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P98 {
	A_SEQUENCE_OF(struct NGAP_SecurityContext_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P98_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P99 {
	A_SEQUENCE_OF(struct NGAP_SecurityIndication_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P99_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P100 {
	A_SEQUENCE_OF(struct NGAP_SecurityResult_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P100_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P101 {
	A_SEQUENCE_OF(struct NGAP_ServedGUAMIItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P101_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P102 {
	A_SEQUENCE_OF(struct NGAP_ServiceAreaInformation_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P102_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P103 {
	A_SEQUENCE_OF(struct NGAP_SingleTNLInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P103_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P104 {
	A_SEQUENCE_OF(struct NGAP_SliceSupportItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P104_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P105 {
	A_SEQUENCE_OF(struct NGAP_S_NSSAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P105_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P106 {
	A_SEQUENCE_OF(struct NGAP_SONConfigurationTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P106_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P107 {
	A_SEQUENCE_OF(struct NGAP_SONInformationReply_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P107_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P108 {
	A_SEQUENCE_OF(struct NGAP_SourceNGRANNode_ToTargetNGRANNode_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P108_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P109 {
	A_SEQUENCE_OF(struct NGAP_SourceRANNodeID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P109_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P110 {
	A_SEQUENCE_OF(struct NGAP_SupportedTAItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P110_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P111 {
	A_SEQUENCE_OF(struct NGAP_TAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P111_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P112 {
	A_SEQUENCE_OF(struct NGAP_TAIBroadcastEUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P112_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P113 {
	A_SEQUENCE_OF(struct NGAP_TAIBroadcastNR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P113_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P114 {
	A_SEQUENCE_OF(struct NGAP_TAICancelledEUTRA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P114_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P115 {
	A_SEQUENCE_OF(struct NGAP_TAICancelledNR_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P115_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P116 {
	A_SEQUENCE_OF(struct NGAP_RRCInactiveTAIItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P116_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P117 {
	A_SEQUENCE_OF(struct NGAP_TargeteNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P117_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P118 {
	A_SEQUENCE_OF(struct NGAP_TargetNGRANNode_ToSourceNGRANNode_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P118_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P119 {
	A_SEQUENCE_OF(struct NGAP_TargetRANNodeID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P119_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P120 {
	A_SEQUENCE_OF(struct NGAP_TNLAssociationItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P120_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P121 {
	A_SEQUENCE_OF(struct NGAP_TNLInformationItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P121_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P122 {
	A_SEQUENCE_OF(struct NGAP_TraceActivation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P122_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P123 {
	A_SEQUENCE_OF(struct NGAP_UEAggregateMaximumBitRate_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P123_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P124 {
	A_SEQUENCE_OF(struct NGAP_UE_associatedLogicalNG_ConnectionItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P124_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P125 {
	A_SEQUENCE_OF(struct NGAP_UE_NGAP_ID_pair_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P125_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P126 {
	A_SEQUENCE_OF(struct NGAP_UEPresenceInAreaOfInterestItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P126_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P127 {
	A_SEQUENCE_OF(struct NGAP_UESecurityCapabilities_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P127_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P128 {
	A_SEQUENCE_OF(struct NGAP_UnavailableGUAMIItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P128_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P129 {
	A_SEQUENCE_OF(struct NGAP_UserLocationInformationEUTRA_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P129_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P130 {
	A_SEQUENCE_OF(struct NGAP_UserLocationInformationN3IWF_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P130_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P131 {
	A_SEQUENCE_OF(struct NGAP_UserLocationInformationNR_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P131_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P132 {
	A_SEQUENCE_OF(struct NGAP_UserPlaneSecurityInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P132_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P133 {
	A_SEQUENCE_OF(struct NGAP_XnExtTLA_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P133_t;
typedef struct NGAP_ProtocolExtensionContainer_5591P134 {
	A_SEQUENCE_OF(struct NGAP_XnTNLConfigurationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ProtocolExtensionContainer_5591P134_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P0;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P0_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P0_1[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P1;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P1_specs_3;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P1_3[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P2;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P2_specs_5;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P2_5[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P3;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P3_specs_7;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P3_7[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P4;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P4_specs_9;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P4_9[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P5;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P5_specs_11;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P5_11[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P6;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P6_specs_13;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P6_13[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P7;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P7_specs_15;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P7_15[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P8;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P8_specs_17;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P8_17[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P9;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P9_specs_19;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P9_19[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P10;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P10_specs_21;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P10_21[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P11;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P11_specs_23;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P11_23[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P12;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P12_specs_25;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P12_25[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P13;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P13_specs_27;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P13_27[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P14;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P14_specs_29;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P14_29[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P15;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P15_specs_31;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P15_31[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P16;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P16_specs_33;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P16_33[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P17;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P17_specs_35;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P17_35[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P18;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P18_specs_37;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P18_37[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P19;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P19_specs_39;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P19_39[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P20;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P20_specs_41;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P20_41[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P21;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P21_specs_43;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P21_43[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P22;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P22_specs_45;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P22_45[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P23;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P23_specs_47;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P23_47[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P24;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P24_specs_49;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P24_49[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P25;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P25_specs_51;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P25_51[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P26;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P26_specs_53;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P26_53[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P27;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P27_specs_55;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P27_55[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P28;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P28_specs_57;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P28_57[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P29;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P29_specs_59;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P29_59[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P30;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P30_specs_61;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P30_61[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P31;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P31_specs_63;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P31_63[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P32;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P32_specs_65;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P32_65[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P33;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P33_specs_67;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P33_67[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P34;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P34_specs_69;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P34_69[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P35;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P35_specs_71;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P35_71[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P36;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P36_specs_73;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P36_73[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P37;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P37_specs_75;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P37_75[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P38;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P38_specs_77;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P38_77[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P39;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P39_specs_79;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P39_79[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P40;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P40_specs_81;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P40_81[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P41;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P41_specs_83;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P41_83[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P42;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P42_specs_85;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P42_85[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P43;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P43_specs_87;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P43_87[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P44;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P44_specs_89;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P44_89[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P45;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P45_specs_91;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P45_91[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P46;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P46_specs_93;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P46_93[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P47;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P47_specs_95;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P47_95[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P48;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P48_specs_97;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P48_97[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P49;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P49_specs_99;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P49_99[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P50;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P50_specs_101;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P50_101[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P51;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P51_specs_103;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P51_103[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P52;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P52_specs_105;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P52_105[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P53;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P53_specs_107;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P53_107[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P54;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P54_specs_109;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P54_109[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P55;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P55_specs_111;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P55_111[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P56;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P56_specs_113;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P56_113[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P57;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P57_specs_115;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P57_115[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P58;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P58_specs_117;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P58_117[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P59;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P59_specs_119;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P59_119[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P60;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P60_specs_121;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P60_121[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P61;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P61_specs_123;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P61_123[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P62;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P62_specs_125;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P62_125[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P63;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P63_specs_127;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P63_127[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P64;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P64_specs_129;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P64_129[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P65;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P65_specs_131;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P65_131[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P66;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P66_specs_133;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P66_133[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P67;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P67_specs_135;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P67_135[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P68;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P68_specs_137;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P68_137[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P69;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P69_specs_139;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P69_139[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P70;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P70_specs_141;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P70_141[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P71;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P71_specs_143;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P71_143[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P72;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P72_specs_145;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P72_145[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P73;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P73_specs_147;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P73_147[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P74;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P74_specs_149;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P74_149[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P75;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P75_specs_151;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P75_151[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P76;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P76_specs_153;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P76_153[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P77;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P77_specs_155;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P77_155[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P78;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P78_specs_157;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P78_157[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P79;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P79_specs_159;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P79_159[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P80;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P80_specs_161;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P80_161[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P81;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P81_specs_163;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P81_163[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P82;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P82_specs_165;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P82_165[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P83;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P83_specs_167;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P83_167[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P84;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P84_specs_169;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P84_169[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P85;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P85_specs_171;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P85_171[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P86;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P86_specs_173;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P86_173[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P87;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P87_specs_175;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P87_175[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P88;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P88_specs_177;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P88_177[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P89;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P89_specs_179;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P89_179[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P90;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P90_specs_181;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P90_181[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P91;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P91_specs_183;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P91_183[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P92;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P92_specs_185;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P92_185[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P93;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P93_specs_187;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P93_187[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P94;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P94_specs_189;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P94_189[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P95;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P95_specs_191;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P95_191[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P96;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P96_specs_193;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P96_193[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P97;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P97_specs_195;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P97_195[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P98;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P98_specs_197;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P98_197[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P99;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P99_specs_199;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P99_199[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P100;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P100_specs_201;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P100_201[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P101;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P101_specs_203;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P101_203[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P102;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P102_specs_205;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P102_205[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P103;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P103_specs_207;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P103_207[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P104;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P104_specs_209;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P104_209[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P105;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P105_specs_211;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P105_211[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P106;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P106_specs_213;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P106_213[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P107;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P107_specs_215;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P107_215[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P108;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P108_specs_217;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P108_217[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P109;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P109_specs_219;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P109_219[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P110;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P110_specs_221;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P110_221[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P111;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P111_specs_223;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P111_223[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P112;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P112_specs_225;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P112_225[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P113;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P113_specs_227;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P113_227[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P114;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P114_specs_229;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P114_229[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P115;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P115_specs_231;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P115_231[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P116;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P116_specs_233;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P116_233[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P117;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P117_specs_235;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P117_235[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P118;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P118_specs_237;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P118_237[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P119;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P119_specs_239;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P119_239[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P119_constr_239;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P120;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P120_specs_241;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P120_241[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P120_constr_241;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P121;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P121_specs_243;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P121_243[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P121_constr_243;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P122;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P122_specs_245;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P122_245[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P122_constr_245;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P123;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P123_specs_247;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P123_247[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P123_constr_247;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P124;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P124_specs_249;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P124_249[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P124_constr_249;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P125;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P125_specs_251;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P125_251[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P125_constr_251;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P126;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P126_specs_253;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P126_253[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P126_constr_253;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P127;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P127_specs_255;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P127_255[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P127_constr_255;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P128;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P128_specs_257;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P128_257[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P128_constr_257;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P129;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P129_specs_259;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P129_259[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P129_constr_259;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P130;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P130_specs_261;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P130_261[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P130_constr_261;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P131;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P131_specs_263;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P131_263[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P131_constr_263;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P132;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P132_specs_265;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P132_265[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P132_constr_265;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P133;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P133_specs_267;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P133_267[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P133_constr_267;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolExtensionContainer_5591P134;
extern asn_SET_OF_specifics_t asn_SPC_NGAP_ProtocolExtensionContainer_5591P134_specs_269;
extern asn_TYPE_member_t asn_MBR_NGAP_ProtocolExtensionContainer_5591P134_269[1];
extern asn_per_constraints_t asn_PER_type_NGAP_ProtocolExtensionContainer_5591P134_constr_269;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
