/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_RRCInactiveAssistanceInformation.h"

#include "NGAP_ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_NGAP_RRCInactiveAssistanceInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_RRCInactiveAssistanceInformation, uEIdentityIndexValue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_UEIdentityIndexValue,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEIdentityIndexValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_RRCInactiveAssistanceInformation, uESpecificDRX),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_UESpecificDRX,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uESpecificDRX"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_RRCInactiveAssistanceInformation, periodicRegistrationUpdateTimer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_PeriodicRegistrationUpdateTimer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"periodicRegistrationUpdateTimer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_RRCInactiveAssistanceInformation, mICOModeIndication),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_MICOModeIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mICOModeIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_RRCInactiveAssistanceInformation, tAIList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_RRCInactiveTAIList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tAIList"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_RRCInactiveAssistanceInformation, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_5591P97,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_RRCInactiveAssistanceInformation_oms_1[] = { 5 };
static const ber_tlv_tag_t asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_RRCInactiveAssistanceInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uEIdentityIndexValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uESpecificDRX */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* periodicRegistrationUpdateTimer */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mICOModeIndication */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* tAIList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_NGAP_RRCInactiveAssistanceInformation_specs_1 = {
	sizeof(struct NGAP_RRCInactiveAssistanceInformation),
	offsetof(struct NGAP_RRCInactiveAssistanceInformation, _asn_ctx),
	asn_MAP_NGAP_RRCInactiveAssistanceInformation_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_NGAP_RRCInactiveAssistanceInformation_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_RRCInactiveAssistanceInformation = {
	"RRCInactiveAssistanceInformation",
	"RRCInactiveAssistanceInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1,
	sizeof(asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1)
		/sizeof(asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1[0]), /* 1 */
	asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1)
		/sizeof(asn_DEF_NGAP_RRCInactiveAssistanceInformation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_RRCInactiveAssistanceInformation_1,
	6,	/* Elements count */
	&asn_SPC_NGAP_RRCInactiveAssistanceInformation_specs_1	/* Additional specs */
};

