/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_NrintegrityProtectionAlgorithms_H_
#define	_NGAP_NrintegrityProtectionAlgorithms_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NGAP_NrintegrityProtectionAlgorithms */
typedef BIT_STRING_t	 NGAP_NrintegrityProtectionAlgorithms_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_NrintegrityProtectionAlgorithms_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_NrintegrityProtectionAlgorithms;
asn_struct_free_f NGAP_NrintegrityProtectionAlgorithms_free;
asn_struct_print_f NGAP_NrintegrityProtectionAlgorithms_print;
asn_constr_check_f NGAP_NrintegrityProtectionAlgorithms_constraint;
ber_type_decoder_f NGAP_NrintegrityProtectionAlgorithms_decode_ber;
der_type_encoder_f NGAP_NrintegrityProtectionAlgorithms_encode_der;
xer_type_decoder_f NGAP_NrintegrityProtectionAlgorithms_decode_xer;
xer_type_encoder_f NGAP_NrintegrityProtectionAlgorithms_encode_xer;
oer_type_decoder_f NGAP_NrintegrityProtectionAlgorithms_decode_oer;
oer_type_encoder_f NGAP_NrintegrityProtectionAlgorithms_encode_oer;
per_type_decoder_f NGAP_NrintegrityProtectionAlgorithms_decode_uper;
per_type_encoder_f NGAP_NrintegrityProtectionAlgorithms_encode_uper;
per_type_decoder_f NGAP_NrintegrityProtectionAlgorithms_decode_aper;
per_type_encoder_f NGAP_NrintegrityProtectionAlgorithms_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_NrintegrityProtectionAlgorithms_H_ */
#include <asn_internal.h>
