/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_PDUSessionResourceModifyRequestTransfer_H_
#define	_NGAP_PDUSessionResourceModifyRequestTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_BitRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_UPTransportLayerInformation;
struct NGAP_QosFlowAddOrModifyRequestList;
struct NGAP_QosFlowList;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_PDUSessionResourceModifyRequestTransfer */
typedef struct NGAP_PDUSessionResourceModifyRequestTransfer {
	NGAP_BitRate_t	*pDUSessionAggregateMaximumBitRate;	/* OPTIONAL */
	struct NGAP_UPTransportLayerInformation	*uL_NGU_UP_TNLInformation;	/* OPTIONAL */
	struct NGAP_QosFlowAddOrModifyRequestList	*qosFlowAddOrModifyRequestList;	/* OPTIONAL */
	struct NGAP_QosFlowList	*qosFlowToReleaseList;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_PDUSessionResourceModifyRequestTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_PDUSessionResourceModifyRequestTransfer_H_ */
#include <asn_internal.h>
