/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NGAP_PDUSessionResourceModifyRequestTransfer.h"

#include "NGAP_UPTransportLayerInformation.h"
#include "NGAP_QosFlowAddOrModifyRequestList.h"
#include "NGAP_QosFlowList.h"
#include "NGAP_ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_NGAP_PDUSessionResourceModifyRequestTransfer_1[] = {
	{ ATF_POINTER, 5, offsetof(struct NGAP_PDUSessionResourceModifyRequestTransfer, pDUSessionAggregateMaximumBitRate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDUSessionAggregateMaximumBitRate"
		},
	{ ATF_POINTER, 4, offsetof(struct NGAP_PDUSessionResourceModifyRequestTransfer, uL_NGU_UP_TNLInformation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NGAP_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-NGU-UP-TNLInformation"
		},
	{ ATF_POINTER, 3, offsetof(struct NGAP_PDUSessionResourceModifyRequestTransfer, qosFlowAddOrModifyRequestList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_QosFlowAddOrModifyRequestList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qosFlowAddOrModifyRequestList"
		},
	{ ATF_POINTER, 2, offsetof(struct NGAP_PDUSessionResourceModifyRequestTransfer, qosFlowToReleaseList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_QosFlowList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qosFlowToReleaseList"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_PDUSessionResourceModifyRequestTransfer, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_5591P74,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_PDUSessionResourceModifyRequestTransfer_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_PDUSessionResourceModifyRequestTransfer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pDUSessionAggregateMaximumBitRate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uL-NGU-UP-TNLInformation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* qosFlowAddOrModifyRequestList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* qosFlowToReleaseList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_NGAP_PDUSessionResourceModifyRequestTransfer_specs_1 = {
	sizeof(struct NGAP_PDUSessionResourceModifyRequestTransfer),
	offsetof(struct NGAP_PDUSessionResourceModifyRequestTransfer, _asn_ctx),
	asn_MAP_NGAP_PDUSessionResourceModifyRequestTransfer_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_NGAP_PDUSessionResourceModifyRequestTransfer_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer = {
	"PDUSessionResourceModifyRequestTransfer",
	"PDUSessionResourceModifyRequestTransfer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1,
	sizeof(asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1)
		/sizeof(asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1[0]), /* 1 */
	asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1)
		/sizeof(asn_DEF_NGAP_PDUSessionResourceModifyRequestTransfer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PDUSessionResourceModifyRequestTransfer_1,
	5,	/* Elements count */
	&asn_SPC_NGAP_PDUSessionResourceModifyRequestTransfer_specs_1	/* Additional specs */
};

