/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_RRCInactiveAssistanceInformation_H_
#define	_NGAP_RRCInactiveAssistanceInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_UEIdentityIndexValue.h"
#include "NGAP_UESpecificDRX.h"
#include "NGAP_PeriodicRegistrationUpdateTimer.h"
#include "NGAP_MICOModeIndication.h"
#include "NGAP_RRCInactiveTAIList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_ProtocolExtensionContainer;

/* NGAP_RRCInactiveAssistanceInformation */
typedef struct NGAP_RRCInactiveAssistanceInformation {
	NGAP_UEIdentityIndexValue_t	 uEIdentityIndexValue;
	NGAP_UESpecificDRX_t	 uESpecificDRX;
	NGAP_PeriodicRegistrationUpdateTimer_t	 periodicRegistrationUpdateTimer;
	NGAP_MICOModeIndication_t	 mICOModeIndication;
	NGAP_RRCInactiveTAIList_t	 tAIList;
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_RRCInactiveAssistanceInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_RRCInactiveAssistanceInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_RRCInactiveAssistanceInformation_H_ */
#include <asn_internal.h>
