/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/r14.4.0/38413-e40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGAP_CellIDListForRestart_H_
#define	_NGAP_CellIDListForRestart_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_CellIDListForRestart_PR {
	NGAP_CellIDListForRestart_PR_NOTHING,	/* No components present */
	NGAP_CellIDListForRestart_PR_eUTRA_CGIListforRestart,
	NGAP_CellIDListForRestart_PR_nR_CGIListforRestart
	/* Extensions may appear below */
	
} NGAP_CellIDListForRestart_PR;

/* Forward declarations */
struct NGAP_EUTRA_CGIList;
struct NGAP_NR_CGIList;

/* NGAP_CellIDListForRestart */
typedef struct NGAP_CellIDListForRestart {
	NGAP_CellIDListForRestart_PR present;
	union NGAP_CellIDListForRestart_u {
		struct NGAP_EUTRA_CGIList	*eUTRA_CGIListforRestart;
		struct NGAP_NR_CGIList	*nR_CGIListforRestart;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_CellIDListForRestart_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_CellIDListForRestart;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_CellIDListForRestart_H_ */
#include <asn_internal.h>
