#ifndef __COMMONJSONKEY__H
#define __COMMONJSONKEY__H

#ifdef __cplusplus
extern "C"
{
#endif

#define JSONKEY_4G_IMSI                         "imsi"
#define JSONKEY_4G_EBI                          "ebi"
#define JSONKEY_4G_APN                          "apn"
#define JSONKEY_4G_GUMMEI                       "gummei"
#define JSONKEY_4G_GUMMEI_PLMNID                "plmnId"
#define JSONKEY_4G_GUMMEI_PLMNID_MCC            "mcc"
#define JSONKEY_4G_GUMMEI_PLMNID_MNC            "mnc"
#define JSONKEY_4G_GUMMEI_MMEGID                "MMEGid"
#define JSONKEY_4G_GUMMEI_MMECODE               "MMECode"
#define JSONKEY_4G_SERVINGNETWORK               "servingNetwork"
#define JSONKEY_4G_SERVINGNETWORK_MMC           "mcc"
#define JSONKEY_4G_SERVINGNETWORK_MNC           "mnc"
#define JSONKEY_4G_ULI                          "userLocationInfo"
#define JSONKEY_4G_ULI_EUTRAL                   "eutraLocation"
#define JSONKEY_4G_ULI_EUTRAL_TAI               "tai"
#define JSONKEY_4G_ULI_EUTRAL_TAI_PLMNID        "plmnId"
#define JSONKEY_4G_ULI_EUTRAL_TAI_PLMNID_MCC    "mcc"
#define JSONKEY_4G_ULI_EUTRAL_TAI_PLMNID_MNC    "mnc"
#define JSONKEY_4G_ULI_EUTRAL_TAI_TAC           "tac"
#define JSONKEY_4G_ULI_EUTRAL_ECGI              "ecgi"
#define JSONKEY_4G_ULI_EUTRAL_ECGI_PLMNID       "plmnId"
#define JSONKEY_4G_ULI_EUTRAL_ECGI_PLMNID_MCC   "mcc"
#define JSONKEY_4G_ULI_EUTRAL_ECGI_PLMNID_MNC   "mnc" 
#define JSONKEY_4G_ULI_EUTRAL_ECGI_EUTRACELLID  "eutraCellId"
#define JSONKEY_4G_ULI_PRESENCE                 "uliPresence"
#define JSONKEY_4G_PCO                          "pco"
#define JSONKEY_4G_PAA                          "paa"
#define JSONKEY_4G_PDN                          "pdn"
#define JSONKEY_4G_PDN_PDNTYPE                  "pdnType"
#define JSONKEY_4G_PDN_PAA                      "paa"
#define JSONKEY_4G_PDN_PAA_PDNTYPE              "pdnType"
#define JSONKEY_4G_PDN_PAA_ADDR                 "addr"
#define JSONKEY_4G_PDN_PAA_ADDR6                "addr6"
#define JSONKEY_4G_PDN_PAA_LEN                  "len"
#define JSONKEY_4G_PDN_AMBR                     "ambr"
#define JSONKEY_4G_PDN_AMBR_UPLINK              "uplink"
#define JSONKEY_4G_PDN_AMBR_DOWMLINK            "downlink"
#define JSONKEY_4G_RATTYPE                      "ratType"
    #define RATTYPE_EUTRA                       "EUTRA"
#define JSONKEY_4G_UETIMEZONE                   "ueTimeZone"
#define JSONKEY_4G_M_BEARER_CTX                 "modified_bearer_contexts"
#define JSONKEY_4G_M_BEARER_CTX_EBI             "ebi"
#define JSONKEY_4G_M_BEARER_CTX_ENB_S1U_TEID    "enb_s1u_teid"
#define JSONKEY_4G_M_BEARER_CTX_ENB_S1U_IP      "enb_s1u_ip"
#define JSONKEY_4G_M_BEARER_CTX_ENB_S1U_IP_ADDR "addr"
#define JSONKEY_4G_M_BEARER_CTX_ENB_S1U_IP_ADDR6 "addr6"
#define JSONKEY_4G_M_BEARER_CTX_ENB_S1U_IP_IPV6 "ipv6"
#define JSONKEY_4G_M_BEARER_CTX_ENB_S1U_IP_IPV4 "ipv4"
#define JSONKEY_4G_SGW_S1U_IP_IPV4              "sgw_s1u_ipv4"
#define JSONKEY_4G_SGW_S1U_IP_IPV6              "sgw_s1u_ipv6"
#define JSONKEY_4G_SGW_S1U_TEID                 "sgw_s1u_teid"
#define JSONKEY_5G_SM_CONTEXT_UPDATE_TYPE       "sm_context_update_type"

#define JSONKEY_5G_SUPI                         "supi"
#define JSONKEY_5G_UnAuthenticatedSupi          "unauthenticatedSupi"
#define JSONKEY_5G_Pei                          "pei"
#define JSONKEY_5G_GPSI                         "gpsi"
#define JSONKEY_5G_PDUSessionID                 "pduSessionId"
#define JSONKEY_5G_DNN                          "dnn"
#define JSONKEY_5G_sNssai                       "sNssai"
#define JSONKEY_5G_HplmnsNssai                  "hplmnSnssai"
#define JSONKEY_5G_ServingNfID                  "servingNfId"//M
#define JSONKEY_5G_GUAMI                        "guami"
#define JSONKEY_5G_ServiceName                  "serviceName"
#define JSONKEY_5G_RequestType                  "requestType"
#define JSONKEY_5G_N1SmMsg                      "n1SmMsg"
#define JSONKEY_5G_AnType                       "anType"
#define JSONKEY_5G_RatType                      "ratType"
#define JSONKEY_5G_PresenceInLadn               "presenceInLadn"
#define JSONKEY_5G_UeTimeZone                   "ueTimeZone"
#define JSONKEY_5G_SmContextStatusUri           "smContextStatusUri"
#define JSONKEY_5G_HSmfUri                      "hSmfUri"
#define JSONKEY_5G_OldPduSessionId              "oldPduSessionId"
#define JSONKEY_5G_PduSessionsActivateList      "pduSessionsActivateList"
#define JSONKEY_5G_UeEpsPdnConnection           "ueEpsPdnConnection"
#define JSONKEY_5G_HoState                      "hoState"
#define JSONKEY_5G_AdditionalHsmfUri            "additionalHsmfUri"
#define JSONKEY_5G_PcfId                        "pcfId"
#define JSONKEY_5G_NrfUri                       "nrfUri"
#define JSONKEY_5G_SupportedFeatures            "supportedFeatures"
#define JSONKEY_5G_SelMode                      "selMode"
#define JSONKEY_5G_BackupAmfInfo                "backupAmfInfo"
#define JSONKEY_5G_TraceData                    "traceData"
#define JSONKEY_5G_EpsInterworkingInd           "epsInterworkingInd"

#ifdef __cplusplus
}
#endif 

#endif /** __COMMONJSONKEY__H*/
