---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: testing
    service: smf
  name: smf
  namespace: free5gc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: smf
    nodePort: 31780
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: smf
  sessionAffinity: None
  type: NodePort
