apiVersion: apps/v1
kind: Deployment
metadata:
  name: u1-u2-deployment
  namespace: nctu5gc
  labels:
    app: u1u2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: u1u2
  template:
    metadata:
      labels:
        app: u1u2
    spec:
      containers:
      - name: nextepc-u1
        stdin: true
        tty: true
        image: ubuntu:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
      - name: nextepc-u2
        stdin: true
        tty: true
        image: ubuntu:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
