---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: testing
    app: webui
  name: webui-np
  namespace: free5gc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: webui
    nodePort: 31727
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webui
  sessionAffinity: None
  type: NodePort
