/*
 * Minimal Pet Store Example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"syscall"
)

var unixConn *net.UnixConn
var err error

var smContextCreateRaddr = net.UnixAddr{
	Name: "/tmp/smf_smContextCreate.csock",
	Net:  "unixgram",
}

var smContextCreateLaddr = net.UnixAddr{
	Name: "/tmp/smf_smContextCreate.gsock",
	Net:  "unixgram",
}

func init() {
	if err != nil {
		log.Fatal(err)
		return
	}
	syscall.Unlink(smContextCreateLaddr.String())
	unixConn, err = net.DialUnix("unixgram", &smContextCreateLaddr, &smContextCreateRaddr)
	if err != nil {
		log.Fatal(err)
		return
	}
}

func SMContextCreate(w http.ResponseWriter, r *http.Request) {
	var buf []byte
	buf = make([]byte, 1000)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	r.Body.Read(buf)
	_, err := unixConn.Write(buf)
	if err != nil {
		log.Fatal(err)
	}
	len, _, err2 := unixConn.ReadFromUnix(buf)
	if err2 != nil {
		log.Fatal(err2)
	}
	fmt.Fprintln(w, string(buf[0:len]))
}
