/*
 * Minimal Pet Store Example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"flag"
	"log"
	"net/http"
	"strconv"

	"golang.org/x/net/http2"
)

var (
	ip   string
	port uint
)

func init() {
	flag.StringVar(&ip, "ip", "localhost", "ip address of sbi server")
	flag.UintVar(&port, "port", 8080, "port")
	flag.Parse()
}

func main() {
	var server http.Server
	server.Addr = ip + ":" + strconv.Itoa(int(port))
	router := NewRouter()
	http.Handle("/", router)

	http2.ConfigureServer(&server, &http2.Server{})

	log.Fatal(server.ListenAndServe())

}
