/*
 * Minimal Pet Store Example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"net/http"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(route.HandlerFunc)
	}

	return router
}

var routes = Routes{
	Route{
		"SMContextCreate",
		"POST",
		"/nsmf-pdusession/v1/sm-contexts",
		SMContextCreate,
	},
	Route{
		"SMContextUpdate",
		"POST",
		"/nsmf-pdusession/v1/sm-contexts/modify",
		SMContextUpdate,
	},
	Route{
		"SMContextRelease",
		"POST",
		"/nsmf-pdusession/v1/sm-contexts/release",
		SMContextRelease,
	},
	Route{
		"SMContextRetrieve",
		"POST",
		"/nsmf-pdusession/v1/sm-contexts/retrieve",
		SMContextRetrieve,
	},
}
